### ISSUE TITLE
defineExpose for methods

### ISSUE THREAD

**Issue by szsolutions** [tomimandalap/vue3-barcode-qrcode-reader#1]
Hi 

Could you expose the method "onCanPlay" to start the scanningprocess from a parent component?

Thanks
Regards

**Comment by tomimandalap** [comment]
Yes I can do it. Maybe at the weekend I will update to add the defineExpose method.

If you continue the conversation, you can reach out on my social media.

Thank You.
Regards

**Comment by tomimandalap** [comment]
CHANGE REQUEST

**[CHANGELOG]**

- Adding defineExpose method onCanPlay, onCanStop, onReset, onChangeFacemode
- Adding props showOnStream
- Update version 1.0.15

**Comment by tomimandalap** [comment]
CHANGE REQUEST

**[CHANGELOG]**

- Adding defineExpose method onCanPlay, onCanStop, onReset, onChangeFacemode
- Adding props showOnStream
- Update version 1.0.15

**PR DONE**
https://github.com/tomimandalap/vue3-barcode-qrcode-reader/commit/859e56993e8b9280334892dcc880b358bc462bca
